presets:
  - name: photo_effect_simple
    metadata:
      category: "photo_effects"
      description: "Training configuration for simple photo effects"
      flexible: true
      stable: true
      version: "1.0"
    parameters:
      learning_rate: 1e-4
      max_steps: 2000
      min_snr_gamma: 5.0
      noise_offset: 0.1
      save_every_n_steps: 100
      sample_every_n_steps: 500
      network:
        alpha: 32
        dim: 32
        module: networks.lora_flux
      optimizer:
        name: pytorch_optimizer.Ranger21
        args:
          betas: [0.9, 0.999]
          weight_decay: 0.1
          num_iterations: 2000
      scheduler:
        name: cosine_with_restarts
        cycles: 2
  - name: photo_effect_complex
    metadata:
      category: "photo_effects"
      description: "Training configuration for complex photo effects"
      flexible: true
      stable: false
      version: "0.1"
    inherits:
      - "photo_effect_simple"
    parameters:
      learning_rate: 5e-5
      max_steps: 2500
      scheduler:
        name: cosine_with_restarts
        cycles: 1
  - name: world_morph
    metadata:
      category: "world_effects"
      description: "Training configuration for world morphing effects"
      flexible: true
      stable: true
      version: "1.0"
    parameters:
      learning_rate: 0.0008
      max_steps: 160
      network:
        alpha: 1
        dim: 4
        module: flux-1-dev/lora
      optimizer:
        name: Adafactor
        args:
          relative_step: false
          scale_parameter: false
          warmup_init: false
      scheduler:
        name: constant_with_warmup
      mixed_precision: bf16
      gradient_accumulation_steps: 1
      loss_type: l2
      prior_loss_weight: 1.0
      guidance_scale: 1.0
      dataset_repeats: 10
      weighting_scheme: uniform
      huber_schedule: snr
      discrete_flow_shift: 3.1582