presets:
  - name: photo_effect_simple
    metadata:
      category: "photo_effects"
      description: "Training configuration for simple photo effects"
      flexible: true
      stable: true
      version: "1.0"
    parameters:
      learning_rate: 1e-4
      max_steps: 2000
      min_snr_gamma: 5.0
      noise_offset: 0.1
      save_every_n_steps: 100
      sample_every_n_steps: 500
      network:
        alpha: 32
        dim: 32
        module: networks.lora_flux
      optimizer:
        name: pytorch_optimizer.Ranger21
        args:
          betas: [0.9, 0.999]
          weight_decay: 0.1
          num_iterations: 2000
      scheduler:
        name: cosine_with_restarts
        cycles: 2
  - name: photo_effect_complex
    metadata:
      category: "photo_effects"
      description: "Training configuration for complex photo effects"
      flexible: true
      stable: false
      version: "0.1"
    inherits:
      - "photo_effect_simple"
    parameters:
      learning_rate: 5e-5
      max_steps: 2500
      scheduler:
        name: cosine_with_restarts
        cycles: 1